# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_R3z5oTQTxvhKyt7OwYfo7UNyRrP7sA4
"""

!pip install yfinance

import yfinance as yahooFinance
 
 
stock= yahooFinance.Ticker("ADANIENT.NS")
 
# Valid options are 1d, 5d, 1mo, 3mo, 6mo, 1y,
# 2y, 5y, 10y and ytd.
print(stock.history(period="6mo"))

import pandas as pd
stock.to_csv('file1.csv')

